spring:
  datasource:
    url: jdbc:sqlite:stock.db
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
    show-sql: false
app:
  auth:
    email: user@example.com
    password: trading-demo
    display-name: 山田太郎
  admin-auth:
    id: admin
    password: admin-demo
    display-name: 管理責任者
